# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190127_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='building_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
    ]
