# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_myperson_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPerson',
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Person')),
                ('last_name', models.CharField(max_length=50)),
            ],
            bases=('shop.person',),
        ),
    ]
