# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181203_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myperson',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='MyPerson',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
