# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='улица, дом, корпус, квартира', max_length=250, verbose_name='Адрес'),
        ),
    ]
